### ISSUE TITLE
ispravak za Mi Pad

### ISSUE THREAD

**Issue by kosckosc** [MASVA/MA-XML-6.0-CROATIAN-master#4]
Sve najbolje u 2015!

uređaj je Mi Pad, MIUI v6 4.12.19

kada se iz postavku odabere Autom. pokretanje
pa se recimo na viber odabere + da se pokrene piše tekst Dopuušteno
![miuiv6 mipad](https://cloud.githubusercontent.com/assets/3097678/5605805/bed4d4e4-9410-11e4-9c27-00c596077cb8.jpg)

**Comment by MASVA** [comment]
hvala
također svako dobro u novo 2015.
ispravljeno
