### ISSUE TITLE
Ne ometaj me

### ISSUE THREAD

**Issue by kosckosc** [MASVA/MA-XML-6.0-CROATIAN-master#5]
Mi3 MIUIv6 zadnji (5.1.30)

settings -> Ne ometaj me

u "Postavke vremena"

piše:
Od 285:00 do 285:00

a trebalo bi pisati sati

![screenshot_2015-02-04-15-32-12](https://cloud.githubusercontent.com/assets/3097678/6042346/2f8cb9dc-ac84-11e4-9059-629c6f7e5a11.jpg)

**Comment by MASVA** [comment]
ispravljeno
