### ISSUE TITLE
Dvije male pogreške

### ISSUE THREAD

**Issue by dakyst** [MASVA/MA-XML-6.0-CROATIAN-master#6]
Evo našao sam dvije male pogreške samo što se tiče razmaka (znam, picajzla sam :D )

Pozdrav!

![screenshot_2015-05-26-18-43-23](https://cloud.githubusercontent.com/assets/12613976/7817889/693df438-03d8-11e5-855a-a560398fcc50.png)
![screenshot_2015-05-26-18-44-57](https://cloud.githubusercontent.com/assets/12613976/7817890/6950c57c-03d8-11e5-96f9-ab30871970e8.png)

**Comment by MASVA** [comment]
jel to koristiš miui V5?
njega ne radim od 8 mjeseca prošle godine

2015-05-26 18:53 GMT+02:00 dakyst <notifications@github.com>:

**Comment by MASVA** [comment]
fixed
